on:
  push:
  workflow_dispatch:

name: test-rspm

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.repo }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, repo: 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'}
          - {os: ubuntu-latest, repo: 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest'}
          - {os: windows-latest, repo: 'https://packagemanager.rstudio.com/all/latest/'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - run: Rscript test.R
        env:
          TESTREPO: ${{ matrix.config.repo }}
